### PR TITLE
AI config

### PR DESCRIPTION
**Pull request by birkelbach**
A couple of tweaks to allow AI colors to be configured.

### CODE REVIEW

**Comment by birkelbach** [comment]
I let my master branch get ahead of makerplane/master so these pull requests are a bit cluttered.  Sorry about that.  I'll try to be better in the future.

**Comment by Maker42** [comment]
Hi Phil,

I don't see the AI colors being read from any config. Is it not there, or did I just miss it?

Not updating the AI when the roll angle changes was an optimization that I think you suggested and I put it in. It's an optimization since we can readily assume that roll and pitch updates will come together from the AHRS.

**Comment by birkelbach** [comment]
More like moved it up to the screen definition file. As it was they were static class members and would be impossible to change from configuration in the future or the screen files now.  The Python scripts that we have now could eventually be morphed into configuration files if we are disciplined in keeping 'code' out of there except for instantiating object, setting configurations and sizes.  So when I think of moving things up to the pfd.py screen file (for example) I think of that as configuration even though it's a python file.

**Comment by Maker42** [comment]
I did previously add a mechanism for display objects to access screen specific configuration file items, so it is possible.
The way you are proposing it, the screen code has to reach into object attributes of the individual widgets, yes?

**Comment by birkelbach** [comment]
The more top-down the flow of information the more reusable the components are at the lower levels.  The less the lower level components rely on upper level things the better in my opinion.  In either case those two colors were static class level members and were impossible to change without updating the AI Class definition.

I remember suggesting eliminating the ROLL update but as I was doing some tests yesterday I decided that it probably wasn't a good idea.  The screen was not updating when only the ROLL was changing and although a slim possibility I think it needs to be right.  It is possible for the PITCH input to freeze and the ROLL data to still be useful.  The update timing calculation that you do should handle the performance issues.

**Comment by birkelbach** [comment]
Also I think that screen level things like update rate and where to find the database information should probably be in the main configuration file but instrument level things like color, size, placement, font etc. should be in the screen definition file and defined per instrument.  I see a day where we have many different screens that are really nothing more than configuration files that end users can just choose from in the main configuration file.  They could also find one close to what they want and just go in and tweak the positions, colors etc.  I don't know if we'll ever get a screen editor but stranger things have happened.

**Pull request merged**
