### PR TITLE
Vv airports

### PR DESCRIPTION
**Pull request by Maker42**
Add airport rendering to VirtualVFR.
Make the VSI tape display VS from FIX DB, instead of
a questionable computation.

### CODE REVIEW

**Comment by neil-d95** [comment]
Question about the VSI display are you showing ft/min or something else. I put in 2000ft/min VSI. The display only showed 400ft/min.

**Comment by Maker42** [comment]
I re-assigned pph to .1 in the VSI tape, because it was maxing out displaying only less than 500 ft/min. That won't work. I didn't realize the VSI indication was meant to match the altimeter tape scale. I think we'll need to think of something else. Maybe changing the altimeter tape scale. That will take some work because the scale is implicitly hard coded into many places in that class. It will take some cleaning up.

**Comment by neil-d95** [comment]
So that scale should change with the size of the display. not sure if we need a minute or go with and 30 seconds prediction maybe? You can max it out that wouldn't be an issue because if you have that climb out you know. Remember the VSI is a trend instrument. On October 30, 2018 at 8:07 AM Garrett Herschleb <notifications@github.com> wrote:  I re-assigned pph to .1 in the VSI tape, because it was maxing out displaying only less than 500 ft/min. That won't work. I didn't realize the VSI indication was meant to match the altimeter tape scale. I think we'll need to think of something else. Maybe changing the altimeter tape scale. That will take some work because the scale is implicitly hard coded into many places in that class. It will take some cleaning up.—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by Maker42** [comment]
Now that we're getting into the subject, I've been thinking that VSI should be expanded to have it's own independent scale. I think systems like these have it right. What do you think?

image

image


image

**Comment by birkelbach** [comment]
I agree.  It should be a separate instrument with separate scale.  I like the little trend scale that we have for other instruments like airspeed or even some engine instruments and the like but for altitude we have a very specific data point for that called VS that should probably be separated.  The timing for the other trend displays should be configurable.  IAS would be much faster than EGT.

**Pull request closed without merging**
