### PR TITLE
Fix imports for new pyavtools package

### PR DESCRIPTION
**Pull request by birkelbach**
I refactored pyAvTools to make it installable via setuptools and/or pip and these changes address the differences in how to import the modules that were moved there.

### CODE REVIEW

**Comment by birkelbach** [comment]
You can ignore those two changes to the yaml files.  It's just easier for me to test with full screen turned off and I accidentally committed them.

**Comment by neil-d95** [comment]
Phil, looking at this commit requires that the pyAvTools be installed through pip correct?

**Comment by birkelbach** [comment]
Yes and we’ve already fixed PyAvTools to properly install.

**Comment by Maker42** [comment]
Kinda in limbo here because the pyAvTools repo is updated and pyEfis is not, causing the two master branches to not work together. Can we get this merged Neil?

**Comment by neil-d95** [comment]
So I started to bring this up when I saw Phils commit the other day, but I got sidetracked. The commit that Phil has in there for will require pip install I'd like to keep the ability to do either a pip install or have the package in an adjacent location. I understand the simplicity of doing to pip install but I also know some folks don't like to install packages until they are committed to keeping it on the system. I know pip uninstall but others like to simply delete the folders.

  On March 11, 2019 at 11:08 AM Garrett Herschleb <notifications@github.com> wrote:
 
 
 Kinda in limbo here because the pyAvTools repo is updated and pyEfis is not, causing the two master branches to not work together. Can we get this merged Neil?

**Comment by Maker42** [comment]
I agree that it would be nicer to not require an install.

I think that can easily be done by adding back the sys.path verbiage in pyEfis.py

**Comment by birkelbach** [comment]
It's pretty easy to do a `pip3 install -e .` to do an 'editable' installation.  This doesn't actually install the package (no files are copied).  It changes the sys.path to point to the directory that you are in when you issue the command.  You don't have to repeat the install after making changes since it points to the directory where the development files are located.  Try it, you'll like it.

In either case pyEfis is broken.  Even the old sys.path stuff isn't going to work without modification unless all the changes to pyavtools are reverted which will make it much more difficult to properly distribute.

**Comment by neil-d95** [comment]
OK, I'll merge it we'll add the code back in to allow the package to be adjacent and not require the pip install.
    In the future a breaking event like this should require everyone to review and agree in the changes like this because these packages have become very dependant on each other.

**Pull request merged**
