### PR TITLE
Pfd

### PR DESCRIPTION
**Pull request by Maker42**
Add an EPFD (EFIS only) screen.
Limit refresh update frequency for CPU usage.
Clean up turn coordinator, and show it on the PFD screens.
Add an indication for standard turn bank angle.
Add value quality indications on turn coordinator.
Give the round gauges some love. Make them draw nicely no matter the size.
Airspeed: Use configured speeds rather than hard coded.

### CODE REVIEW

**Comment by Maker42** [comment]
This pull request solves the slip/skid relative width problem, and a number of other sizing problems
with all the round gauges. Most of the size hard coding has been cleaned up.

**Comment by neil-d95** [comment]
Looks good.  Still missing the EPFD in the display loop. I still need to 
test the movements of everything.


A Thought is to add to the main.yaml screen: option

   EPFD:
     module: screens.epfd
     title: (Description here)
     dbpath: CIFP/FAACIFP18
     indexpath: CIFP/index.bin


Question to anyone what  happened to "[" and "]" changing the Baro I've 
never had any luck using the button.

**Comment by Maker42** [comment]
OK, I can add it into the screen list tomorrow.

Last I checked (not too long ago), the bracket keys worked for me changing the Baro. I'll check again tomorrow.

To use the button, you have to enable the GUI module in FIX, go to the "Sim" tab of the FIX window. There you should see 6 buttons and a dial. If click on "Baro" button in EFIS, rotate the virtual dial in FIX gui, then you should see the baro setting change. Click on the "Baro Done" button in EFIS when it's set.

**Comment by birkelbach** [comment]
The bracket keys got lost in the move from keys in the hooks module to the hmi module.  I'll work on adding an action to get that working again.

**Comment by neil-d95** [comment]
Thanks didn't think I was going crazy. On Mar 31, 2019 9:43 PM, Phil Birkelbach <notifications@github.com> wrote:The bracket keys got lost in the move from keys in the hooks module to the hmi module.  I'll work on adding an action to get that working again.

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.

On Mar 31, 2019 9:43 PM, Phil Birkelbach <notifications@github.com> wrote:The bracket keys got lost in the move from keys in the hooks module to the hmi module.  I'll work on adding an action to get that working again.

**Pull request closed without merging**
