### PR TITLE
Remove AeroCalc package

### PR DESCRIPTION
**Pull request by birkelbach**
We were not using the AeroCalc package in the EFIS.  The license for the AeroCalc package is not strictly open either and we probably shouldn't be doing air data calculations in the EFIS.

### CODE REVIEW

**Comment by neil-d95** [comment]
I had cleared including it with Software Freedom Foundation in regards 
to the license prior to putting it in so the license isn't a problem. 
You might want to consider bringing it into the calculator that I'm sure 
your working one.


Also what is the  (*, True)  being added for my clarification.


Neil

**Comment by birkelbach** [comment]
I do use it in the test nodes that I have been using for testing and if we need to do air data calculations in a FGW plugin it will be included.  I've reached out to Kevin to see if he would fix the issues with PyPi so that it can be installed properly by pip but I guess he got sidetracked.  If he has lost interest we may want to fork it or develop our own.  The air data computer that I'm working on is an 8bit uC so it's of no value there at all.

The *,True that was added to the getItem() function calls tell that function to create the database items if they don't exist.  Without it the function will raise an exception if the key is not in the database.

**Comment by Maker42** [comment]
PITCH and ROLL are in the database, so creating the key if it doesn't exist
is just a kludge fix to an underlying DB initialization issue. Probably a
race condition where the AI is trying to access the database prior to
initialization.

**Comment by neil-d95** [comment]
Comments in red.

On 1/26/19 11:04 AM, Garrett Herschleb wrote:
> PITCH and ROLL are in the database, so creating the key if it doesn't 
> exist
> is just a kludge fix to an underlying DB initialization issue. Probably a
> race condition where the AI is trying to access the database prior to
> initialization.
Kinda of agree with the above. Maybe for the exceptions kick out a 0 and 
log a missing key? This will keep from crashing or hanging the system.
>
> On Sat, Jan 26, 2019 at 8:13 AM Phil Birkelbach <notifications@github.com>
> wrote:
>
> > I do use it in the test nodes that I have been using for testing and 
> if we
> > need to do air data calculations in a FGW plugin it will be 
> included. I've
> > reached out to Kevin to see if he would fix the issues with PyPi so 
> that it
> > can be installed properly by pip but I guess he got sidetracked. If 
> he has
> > lost interest we may want to fork it or develop our own. The air data
> > computer that I'm working on is an 8bit uC so it's of no value there 
> at all.
An 8bit control isn't going to handle the calculation for Density alt or 
TAS. The discussion that I recall I could be wrong was a process in 
FIX-GW to handle these calculations or Do you think we should look at 
adding an external one.

**Comment by birkelbach** [comment]
> On 1/26/19 11:04 AM, Garrett Herschleb wrote: PITCH and ROLL are in the database, so creating the key if it doesn't exist is just a kludge fix to an underlying DB initialization issue. Probably a race condition where the AI is trying to access the database prior to initialization.
> Kinda of agree with the above. Maybe for the exceptions kick out a 0 and log a missing key? This will keep from crashing or hanging the system.

The get_item() calls that we are talking about are not in a race with the initialization routines, they are the initialization routines.  This is how the database gets created.  When the instruments are initialized they call these functions to retrieve items so that they can connect to the signals.  If the items don't exist they are created.  If you just log the missing item or return an error then the instrument object will have to come back a recreate these later.  It will be much more complicated.  If you require the item to exist at the time of calling the get_item() call you can leave off the create=True and it will raise a KeyError exception that you can catch or let it filter up and crash the program, whichever makes more sense for the application.  The instruments might be in a race with each other which is probably why this was crashing for me and not for you guys.  It depends on the order that the instruments are initialized.

**Comment by neil-d95** [comment]
Here is my opinion let's go with something for FIX-GW that is able to be turned on and off via configuration. my 2 cents.

**Comment by birkelbach** [comment]
Agreed.  I may just add some more functions to the compute plugin for this.

**Pull request merged**
