### PR TITLE
Move fix

### PR DESCRIPTION
**Pull request by Maker42**
Moved fix module to pyAvTools.
Changed get_item to be backward compatible.

### CODE REVIEW

**Comment by Maker42** [comment]
Neil this should "fix" your pyAvMap import fix problem. No pun intended whatsoever. None. Zilch. pyAvTools is merged and ready to go.

**Comment by Maker42** [comment]
Good catch Neil.

**Comment by Maker42** [comment]
How do you propose to handle the little import problem you found?
Withdraw the pull request and make another one? Or include the fix in a future, more substantial pull?

**Comment by neil-d95** [comment]
I'll make the change and commit it. Tonight when I'm home.On February 21, 2019 at 3:31 PM Garrett Herschleb <notifications@github.com> wrote:  How do you propose to handle the little import problem you found? Withdraw the pull request and make another one? Or include the fix in a future, more substantial pull?—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.

**Pull request merged**
