### PR TITLE
Add hooks for autopilot and flight director

### PR DESCRIPTION
**Pull request by Maker42**

### CODE REVIEW

**Comment by neil-d95** [comment]
There is still issues around PHNL airport. if you get near the airport. Not major
Traceback (most recent call last):
  File "/home/neil/Project/MakerPlane/testing/pyEfis/instruments/ai/VirtualVfr.py", line 85, in resizeEvent
    self.pov.render(self)
  File "/home/neil/Project/MakerPlane/testing/pyEfis/instruments/ai/VirtualVfr.py", line 689, in render
    (self.gps_lng, self.gps_lat))
  File "/home/neil/Project/MakerPlane/testing/pyEfis/instruments/ai/CIFPObjects.py", line 343, in render
    self.bearing, self.name, self.airport_id, pov.zoom)
  File "/home/neil/Project/MakerPlane/testing/pyEfis/instruments/ai/VirtualVfr.py", line 151, in render_runway
    rwlabels = self.get_runway_labels (name)
  File "/home/neil/Project/MakerPlane/testing/pyEfis/instruments/ai/VirtualVfr.py", line 127, in get_runway_labels
    ret.append(rwnum_string + recip_postfix[postfix])
KeyError: 'W'
Aborted (core dumped)

**Comment by Maker42** [comment]
Aaaahh! Interesting! Big airports might have up to three parallel runways, like 26L, 26C, and 26R. So the post fixes are L, C, and R, and the match up with 08R, 08C, and 08L respectively. But Honolulu has a 26W and a 08W. What on earth is a W postfix? Those runways show on the airport diagram as just dashed line rectangles. Then it dawned on me: they have water runways. One more postfix to consider!

Maybe I should make those a shade of dark blue instead of black.

**Comment by Maker42** [comment]
This is what the water runways look like now. This is runway 22W in Honolulu. The brush color is a dark blue rather than the black of land runways. I'll make a new pull request.

image

**Comment by Maker42** [comment]
The water runways are very easy to miss on the diagram. There are 22L and R, but also a 22W. I had to stare at it and scratch my head for a while before I finally noticed them.

I've highlighted them here.

image

**Comment by neil-d95** [comment]
Nice catch. I have a couple of questions Also are the runways supposed to disappear after you cross the threshold? While testing with FG I noticed the runway jumping left and right a bit. Think it's a rounding, or it's dropping after a set digit or lat and or long.

  On November 29, 2018 at 10:37 AM Garrett Herschleb <notifications@github.com> wrote:
 
 
 The water runways are very easy to miss on the diagram. There are 22L and R, but also a 22W. I had to stare at it and scratch my head for a while before I finally noticed them. 
 I've highlighted them here.

**Comment by Maker42** [comment]
On the subject of disappearing runways, yes, that's part of the implementation. When any of the points in the polygon stop intersecting the plane of view, you either have to reconstruct intermediate points or stop rendering. I figured it wasn't really worth the effort for reconstructing a partial runway at that point the pilot damn well better have visual contact, or he's got the throttle to the wall for a missed approach, neither of which need a virtual VFR rendering. What do you think?

I'm using X-Plane for my testing, and I'm seeing smooth motion, so I wonder if this is an artifact of either FGFS, or the Fix GW plugin?

**Comment by neil-d95** [comment]
It might be the connection to FG I'll look into it since your not seeing it in X-Plane.

**Pull request merged**
