### PR TITLE
Repair Sixpack and implimented  Slip / Skid

### PR DESCRIPTION
**Pull request by neil-d95**
- Fixed
Repaired the sixpack to keep it from crashing when switching, between combined PFD combo and Sixpack screen. 
VSI marks
Screen layout with Menu.
HSI Color 

- Added
Used sixpack to work out the inclinometer slip / skid indication to the turn coordinator. 
Linked to the YAW in FIX-GW.  Max is +/- 5g's full ball deflection.
10,000 foot indicator to the Altimeter.

### CODE REVIEW

**Comment by birkelbach** [comment]
YAW is not correct.  That is a gyroscopic measurement and is given as an Angle in Degrees.  The correct database item is ALAT (Lateral Acceleration).  +/-5 Gs is going to be way to much.  Did you mean 0.5Gs?  I was actually thinking that it would be way less than that.  More like +/-0.1 G but I'm not really sure.  The slip skid is really nothing more than a spirit level with a pretty big radius.  If the slip/skid indicator was a full half circle then 1G would be full deflection.  What full deflection "should" be would be a function of how much of that circle we have in a traditional instrument.  I don't know what that is.

**Comment by birkelbach** [comment]
I've looked everywhere for a slip/skid ranges, with no luck.  That usually means that the answer is obvious and I'm missing something. :-)  I have an idea for how to calculate it.  I may go to the airport and measure what the one in my RV does as well.  I'll let you know the results.

**Comment by Maker42** [comment]
Shouldn't the number of g's for full deflection be a configuration item?

**Comment by neil-d95** [comment]
It should be standard for most aircraft. like buying an instrument TC or slip/skid indicators.

  On January 28, 2019 at 3:34 PM Garrett Herschleb <notifications@github.com> wrote:
 
 
 Shouldn't the number of g's for full deflection be a configuration item?

**Pull request merged**
